spring.application.name=supplierservice

server.port = 8094

# Notice the r2dbc protocol instead of jdbc
spring.r2dbc.url=r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
spring.r2dbc.username=sa
spring.r2dbc.password=password

# Enable H2 console for debugging (runs on a blocking JDBC servlet internally)
spring.h2.console.enabled=true
